### ISSUE TITLE
design the landing page

### ISSUE THREAD

**Issue by talktonok** [BuildForSDGCohort2/Team-128-frontend#1]
use the design I shared with you as a guide

**Comment by Sir-Dazzling** [comment]
wait u shared the design with me? sorry i haven't seen any

**Comment by talktonok** [comment]
@Sir-Dazzling its not you, but will prefer someone to handle the basic HTML CSS while you handle the react aspect?

**Comment by Sir-Dazzling** [comment]
Oh alright

**Comment by mcsepro** [comment]
done
